### ISSUE TITLE
installation fail

### ISSUE THREAD

**Issue by f0r7y** [KnugiHK/WhatsApp-Key-DB-Extractor#10]
Hi
i receive this error
```
Please connect your Android device with USB Debugging enabled:

* daemon not running. starting it now on port 5037 *
* daemon started successfully *

WhatsApp 2.24.3.81 installed

Downloading legacy WhatsApp 2.11.431 to local folder

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17.4M  100 17.4M    0     0  2263k      0  0:00:07  0:00:07 --:--:-- 3474k

Backing up WhatsApp 2.24.3.81
5160 KB/s (55253773 bytes in 10.456s)
Backup complete

Removing WhatsApp 2.24.3.81 skipping data
Success
Removal complete

Installing legacy WhatsApp 2.11.431
4069 KB/s (18329558 bytes in 4.398s)
Success
Install complete! Open Whatsapp, allow the permissions request, if any. Then, press Enter to continue.




Now unlock your device and confirm the backup operation.

Please enter your backup password (leave blank for none) and press Enter:

Exception in thread "main" java.lang.RuntimeException: java.lang.NumberFormatException: For input string: ""
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:233)
        at org.nick.abe.Main.main(Main.java:40)
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:71)
        ... 1 more
[FATAL] ABE failed with 1.
```
On the phone, the leghavcy whatsapp is installed but warning that date and time is incorrect but not true, are correct
Can you help me?
thanks

**Comment by KnugiHK** [comment]
Does this issue help: https://github.com/nelenkov/android-backup-extractor/issues/59 ?
